accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

main/urls.py
from django.urls import path

from . import views

#path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi'),.

app_name = 'main' # main nama folder app nya

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/', views.portfolio, name='portfolio'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path
from story8.views import search, f_data
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # new signup
    path('accounts/', include('django.contrib.auth.urls'), name='login'), #new login
    path('', TemplateView.as_view(template_name='index.html'), name='home'), #home
    path('', include('main.urls'), name='home'),
    path('', include('story8.urls')),
    path('jadwal/', include('story5.urls'), name='story5'), #path untuk ke urls.py nya folder app (main)
    #path('search/', search),
    #path('data/', f_data),
]

story5/urls.py
from django.urls import path

from . import views

#path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi'),.

app_name = 'story5' # main nama folder app nya

urlpatterns = [
    #path('', views.index, name='index'),
    path("jadwal/", views.jadwal, name="jadwal"),
    path ("delete/<int:items_id>/", views.deleteItems, name="delete"),
]

story8/urls.py
from django.urls import path

from . import views


#path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi'),.

app_name = 'story8' # main nama folder app nya

urlpatterns = [
    path('search/', views.search, name="search"),
    path('data', views.f_data, name="data"),

]

accounts/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Hasil(models.Model):
    hari = models.CharField(max_length = 15, default="Unknown")
    tanggal = models.DateField(max_length = 10, default="Unknown")
    waktu = models.TimeField(max_length = 10, default="Unknown")
    kegiatan = models.CharField(max_length= 100, default="Unknown")
    lokasi = models.CharField(max_length = 50, default="Unknown")
    kategori = models.CharField(max_length = 20, default="Unknown")

story8/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

main/views.py
from django.shortcuts import render

#return render(request, 'nama_file.html')


def index(request): #home nama HTML nyaa
    return render(request, 'index.html') #main nama folder yang dalemnya ada home.html nya

def portfolio(request):
    return render(request, 'portfolio.html')

story5/views.py
from django.shortcuts import render, redirect
from .models import Hasil
from django.core.exceptions import ValidationError

# Create your views here.


def deleteItems(request, items_id):
    a = Hasil.objects.get(id=items_id)
    a.delete()
    return redirect("story5:jadwal")

def jadwal(request):
    context = {}
    if request.method == "POST":
        hari = request.POST.get('hari')
        tanggal = request.POST.get('tanggal')
        waktu = request.POST.get('waktu')
        kegiatan = request.POST.get('kegiatan')
        lokasi = request.POST.get('lokasi')
        kategori = request.POST.get('kategori')
        hasil = Hasil(hari=hari, tanggal=tanggal, waktu=waktu, kegiatan=kegiatan, lokasi=lokasi, kategori=kategori)
        try:
            #hasil.clean()
            hasil.save()
        except ValidationError:
            pass
    context['hasilan'] = Hasil.objects.all().order_by('tanggal')    
    return render(request, "jadwal.html", context)

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json


# Create your views here.

def search(request):
    response = {}
    return render(request, 'search.html', response)

def f_data(request):
    arg = request.GET['q']
    urlItem = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    respon = requests.get(urlItem)
    data = json.loads(respon.content)
    return JsonResponse(data)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Shanika Tysha A</title>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 800, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});
</script>
<body>

<div class="container-fluid">
    <img class="img-responsive "img src="{% static 'img/header.png' %}" style="position: fixed;height: 120px;padding-left: 30px;">
</div>

<div class="container-fluid flexnav">
    <div class="wrapper">
 <div class="row row-fluid">
    <div>
        <div class="col-xs-6 navkiri">
            <a href="{% url 'main:portfolio' %}">Projects</a>
        </div>
    </div>
    <div class="col-xs-8">
        <p style="width: 1245px;"></p>
    </div>

    <div>
        <div class="col-xs-6 navkanan" >
            <a href="#contact">Contact</a>
        </div>
    </div>
</div>
</div>
</div>


<div class="home" id="home">
<div class="container">
<!-- <div class="mw-100" id="home">-->

    <!--<div class="isihome">-->
        <img class="mw-100" img src="{% static 'img/homepic.png' %}">
    
    </div>
</div>

</div>




    <div class="about container">
        <div class="row align-middle" style="text-align:left; padding-top:300px ;">
            <div class="col-sm-6">
    <img class="mw-100 img-responsive" img src="{% static 'img/aboutme.png' %}"  >
</div></div>
    <div class="row kosong" style="height: 70px;"></div>
        
    <div class="row align-middle">
    <div class="col-xs-8 col-sm-4  align-left clearfix">
      <img class="mw-100" img src="{% static 'img/fototysha.png' %}" style="border-right: 20px;" >
    </div>
    
    <div class="col-xs-6 col-sm-3 align-self-center">
    <p class="isi" style="line-height: 150%;font-size: 17px;width:500px;">
    My name is Shanika Tysha Anqita (1906305890), people usually call me Tysha.
    I'm a Computer Science Student (class of year 2019) in the Faculty of Computer Science, University of Indonesia.
    My hobbies include graphic design and watching netflix. I like designing stuff because it's therapeutic.
      Most days I design for myself, and on certain days I help a friend out by making them posters, 
      thumbnails, stickers, wallpapers, t-shirt designs, personal brand logos, album covers, etc.
    <br><br>
    </div></div>

</div>

<div class="jadwal">
    <p style="font-size:50px;padding-top: 100px;">Check my classes here!</p>
    <button href="#" class="btn btn-outline-light btn-lg" role="button" >Go to Schedule</button>
</div>





<div class="edu container" id="edu">
    <div class="row align-middle" style="text-align:left; padding-top:300px ;">
        <div class="col-xs-6">
<img class="mw-100 img-responsive" img src="{% static 'img/education.png' %}"  >
</div></div>
    <div class="row kosong" style="height: 50px;"></div>
    <div class="row">
        
          <table class="table-borderless" style="width:100%vmin">
              <tr style="font-size: 20px;">
                <th scope="col"><b>Year</b></th>
                <th scope="col"></th>
                <th scope="col"><b>Education</b></th> 
              </tr>
              <tr style="font-size: 20px;">
                <td scope="col">2019-present</td>
                <th scope="col"><img src="{% static 'img/panah.png' %}" style="padding-left: 30px;height:15px;"></th>
                <td scope="col">Fakultas Ilmu Komputer UI</td>
              </tr>
              <tr style="font-size: 20px;">
                <td scope="col">2016-2019</td>
                <th scope="col"><img src="{% static 'img/panah.png' %}" style="padding-left: 30px;height:15px;"></th>
                <td scope="col">SMA Labschool Kebayoran</td>
              </tr>
              <tr style="font-size: 20px;">
                <td scope="col">2013-2016</td>
                <th scope="col"><img src="{% static 'img/panah.png' %}" style="padding-left: 30px;height:15px;"></th>
                <td scope="col">SMP Labschool Kebayoran</td>
              </tr>
            </table>
        
        </div>
        
    </div>









<div class="container-fluid contact" id="contact" style="visibility: visible;">

  
        <a class="link" href="#home">About me</a>
        <br>
        <a href="#edu">Educational Background</a>
        <br>
        <a href="#exp">Experiences</a>
        <br>
        <a href="#projects">Projects</a>
        <br>


    
    <div class="row kosong" style="height: 50px;"></div>

    <div class="row contactnya" >
        <img class="mw-100 img-responsive" src="{% static 'img/sayhi.png' %}" style="float:left;padding-right: 400px;">
        <div class="row " style="height: 100px;"></div></div>

        <div class="row" style="padding-top:20px;">
            <div class="col-xs-8" style="padding-right: 150px;">
                <p>Email</p>
            </div>
            <div class="col-xs-3">
                <p><a href="mailto:tyshaa46@gmail.com">tyshaa46@gmail.com</a></p>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-8" style="padding-right: 100px;">
                <p>Others</p>
            </div>
            <div class="col-xs-3">
                <img src="{% static 'img/ig.png' %}">
            </div>
            <div class="col-xs-3">
                <img src="{% static 'img/tw.png' %}">
            </div>
            <div class="col-xs-3">
                <img src="{% static 'img/in.png' %}">
            </div>
            <div class="col-xs-3">
                <img src="{% static 'img/be.png' %}">
            </div>
        </div>


        <footer class="panah" style="text-align: center;font-size:50px;transform: rotate(-90deg);padding-top:50px ;">
            <p><a href="#home" style="transform: rotate(-90deg);">➙</a></p>
        
        </footer>

    </div>

</div>


</body>
</html>

main/templates/main/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <script type="text/javascript" src="{% static 'myScript.js' %}"></script>
    <title>My Babies :)</title>
</head>
<body>

    
<div class="flex-container">

<div>
    <a href="{% url 'main:index' %}"><img src="{% static 'img/header.png' %}" style="position: fixed;height: 120px;"></a>
    </div>

</div>




<div class="container-fluid images">
    

<div class="container">
<img src="{% static 'img/1.jpg' %}" style="width: 800px;">
<div class="overlay">Deskripsi</div>
</div>

<p>✺</p>

<div class="container">
<img src="{% static 'img/2.jpg' %}" style="width: 800px;">
<div class="overlay">Deskripsi</div>
</div>

<p>✽</p>

<div class="container">
<img src="{% static 'img/3.jpg' %}" style="width: 800px;">
<div class="overlay">Deskripsi</div>
</div>

<p>✧</p>

<div class="container">
<img src="{% static 'img/4.jpg' %}" style="width: 800px;">
<div class="overlay">Deskripsi</div>
</div>

<p>✷</p>

<div class="container">
<img src="{% static 'img/5.jpg' %}" style="width: 800px;">
<div class="overlay">Deskripsi</div>
</div>

<p>✲</p>

<div class="container">
<img src="{% static 'img/6.jpg' %}" style="width: 800px;">
<div class="overlay">Deskripsi</div>
</div>
</div>

<div class="kosong" style="height: 50px;"></div>
<div class="linku">
<p>➙<a href="https://drive.google.com/file/d/1EhfXVN2m3lnZiy5_yiPpGxhtRUv4HcWe/view">More cool projects on my portfolio!</a></p>
</div>





</body>
</html>

story5/templates/jadwal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

   <!-- Jquery pertama -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

   <!-- popper kedua -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

   <!-- sisanya bootstrap -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/styleJadwal.css' %}">


    <title>Ayo Isi Jadwal!</title>
</head>
<body>

    
<div class="flex-container">

<div>
    <a href="{% url 'main:index' %}"><img src="{% static 'img/header.png' %}" style="position: fixed;height: 120px; z-index:1;display: block;position: fixed,relative;padding-left: 0px"></a>
        <div class="linku" style="text-align: right;padding-top:72px;padding-right:20px;font-size: 45%;">
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">➙ Log Out</a>
                {% else %}
            <a href="{% url 'login' %}">➙ Log In</a>
                {% endif %}
        </div>    
    </div>

</div>




{% if user.is_authenticated %}
<form action="" method="POST" class="was-validated">
    {% csrf_token %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel" style="color: blue;">
                        What's ur sched..
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="bg-white" aria-hidden="true">
                            &times;
                        </span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="bg-white">
                        <input name="hari" type="text" placeholder="Day" required><br>
                        <input name="tanggal" type="date" required><br>
                        <input name="waktu" type="time" required><br>
                        <input name="kegiatan" type="text" placeholder="Task" required><br>
                        <input name="lokasi" type="text" placeholder="Location" required><br>
                        <input name="kategori" type="text" placeholder="Category" required><br>
                        <div class="invalid-feedback">*Please fill out all the field.</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button close" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>


  <div class="container-fluid kosnten" style="background-color: black;">
          <div style="padding-top: 200px;">
        <a>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#exampleModal">
            Add Jadwal!
        </button>
        </a>
    </div>

<div class="notcomp">
    <p>Click on sched when completed...</p>
    <p>✲  ✧  ✽</p>
    
    <a>
        {% for hasil in hasilan %}
        <form action="{% url 'story5:delete' hasil.id %}">
            <button class="tomblo" type="submit" name="delete" style="height: 30vh;width: 40vw;font-size: 25px;">
            <b>{{ hasil.kegiatan  }}</b><br>
                {{ hasil.hari }} ✷ {{ hasil.tanggal }} ✷ {{ hasil.waktu }}<br>
                {{ hasil.lokasi }}<br>
                {{ hasil.kategori }}<br>
            </button>
        </form>
        <p>✲  ✧  ✽</p>
        {% endfor %}
    </a>
</div>
<footer>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</footer>

</div>

{% else %}
<p class="linku "style="padding-top:200px;font-size:30px;">whoops u must login to view my sched :)</p>
{% endif %}




</div>


</body>
</html>

story8/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styleSearch.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Find a Book !</title>
    
    <script type="text/javascript">
        $(document).on({
            ajaxStart: function () {
        $('.none').css('display', 'block');
            },
            ajaxStop: function () {
        $('.none').css('display', 'none');
            }
        });

        $(document).ready(function () {
        $('#myform').submit(function (e) {
            let searchItem = $('.searchbox').val();
            console.log(searchItem);
            let urlItem = '/data?q=' + searchItem;
            
            $.ajax({
                async: true,
                type: 'GET',
                url: urlItem,
                dataType: 'json',
                success: function(searchRes) {
                    console.log(searchRes)
                    $('.status-container').next().addClass('none');
                    $('.status-container').removeClass('none');
                    let bookShelf = searchRes.items;
                    console.log(bookShelf)
                    
                    $('tbody').empty();
                    
                    for (i = 0; i < 10; i++) {
                        let book = bookShelf[i].volumeInfo;
                        var num = $('<td>').text(i + 1);

                        if ('imageLinks' in book == false)
                        var img = $('<td>').text("not found");

                        else {
                            if ('smallThumbnail' in book.imageLinks == false)
                                var img = $('<td>').append($('<img>').attr({
                                    'src': book.imageLinks.thumbnail
                                }));
                            else
                                var img = $('<td>').append($('<img>').attr({
                                    'src': book.imageLinks.smallThumbnail
                                }));
                        }

                        if ('authors' in book == false) var author = $('<td>').text(book.title + '\nby ' + "-");
                        else var author = $('<td>').text(book.title + '\nby ' + book.authors);

                        if ('categories' in book == false) var category = $('<td>').text("-" + '\n ' + book.pageCount + ' pages');
                        else var category = $('<td>').text(book.categories + '\n' + book.pageCount + ' pages');

                        var tr = $('<tr>').append(num, img, author, category);

                        $('tbody').append(tr);
                    }
                },
                
                type: 'GET',
            });
            event.preventDefault();
        })
    });

    </script>

</head>
<body>
    <div class="flex-container">
        <div>
            <a href="{% url 'main:index' %}"><img src="{% static 'img/header.png' %}" style="position: fixed;height: 120px;"></a>
        </div>
    </div>

    <div class="header-searchboxx">
        <p>What are u looking for?</p>
    </div>

    <div class="searchboxx">  
        <form class="mb-2 input-group-append" id="myform">
            <input class="form-control searchbox" type="search" id="books" placeholder="Search a book..." aria-label="Search">
            <button type="submit" class="btn btn-primary btn-submit">Search</button>
        </form>
    </div>


    <div class="result align-l mx-5">
        <div id="res-header" class="flex-left mb-4">
            <div class="text-container" style="padding-top: 80px;">
                <h1 class="text-24 hasil" style="color: #3adf00;font-size: 20px;font-weight: bold;">➙ Search Result</h1>
            </div>
        </div>
        <div class="status-container none" >
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" style="width:10%;">No. </th>
                        <th scope="col" style="width:25%;">Cover</th>
                        <th scope="col" style="width:40%;">Title</th>
                        <th scope="col" style="width:20%;">Category</th>
                    </tr>
                </thead>
                <tbody>
                            
                </tbody>
            </table>
        </div>
    </div>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>